### ISSUE TITLE
Can "long press" be detected?

### ISSUE THREAD

**Issue by llaisdy** [mpizenberg/elm-touch-events#6]
Hello!  Thank you for developing this library.  I am using it as part of zaboco/elm-draggable.

Is there a way to detect a "long press" in Elm (e.g., with this library)?  i.e. a mouse/pointer
down event followed by a period of time without movement.

Best wishes

Ivan

**Comment by mpizenberg** [comment]
Hello there :)

I'm glad this is working for some of your needs. Just as a reminder, elm 0.19 is arriving soon, and I've deprecated this package (cf readme) and moved (+ changed a bit) this to [elm-pointer-events](http://package.elm-lang.org/packages/mpizenberg/elm-pointer-events/latest). More info about why in [this post](https://discourse.elm-lang.org/t/package-for-mouse-touch-pointer-wheel-and-drag-apis/704).

As I explained there, I didn't spend time yet on gestures interpretation. Due to TEA, I think this would require to handle some state in the model. zwilias/elm-touch-events has started something to interpret gestures but limited to swiping to my knowledge.

I think you could try something like emitting a delayed command on touch start with something like:

```
mkDeferredCmd : Time -> a -> Cmd a
mkDeferredCmd delay a =
    Task.perform (always a) (Process.sleep delay)
```

And on touch end, check if the deferred command got already processed or not.

I'd love [to try to do](https://github.com/mpizenberg/elm-pointer-events/issues/5) (or someone else do) a gesture package on top of `elm-pointer-events`. I'm simply lacking time for the moment, and realistically will not be able to tackle this for at least 3-4 months.

Hope this helps you.

**Comment by llaisdy** [comment]
Dear Matthieu

Thanks v much for these comments - very helpful.

I promise to migrate to elm-pointer-events asap! I'll do it as part of implementing this long press.

The delayed command idea is good - and set some flag in the model, which can be removed on mouse move or mouse up; before running, command checks flag is still set.  (My Elm is fairly basic).

Best wishes

Ivan

**Comment by llaisdy** [comment]
It works!  Thanks for your help.  I've just tried it with CustomEventsExample.elm from zaboco/elm-draggable-examples.  I'll upload to github in the next few days and link here for the record.

**Comment by mpizenberg** [comment]
Cool, glad it helped :)
